@extends('templates.master')
@section('content')
    @if($level == "users")
        @include('partials.search.user-list')
    @else
        @switch($activeSearchEngine)
            @case("google")
                @include('partials.search.google')
                @break
            @case("algoliacustom")
                @include('partials.search.algolia-customsearch')
                @break
            @case("algolia")
                @include('partials.search.algolia')
                @break
            @case("algoliainstant")
                @include('partials.search.algolia-instantsearch')
                @break
            @default
                @include('partials.search.wp')
        @endswitch
    @endif
@stop
